### ISSUE TITLE
Setup Android SDK fails

### ISSUE THREAD

**Issue by ash-wtag** [android-actions/setup-android#392]
Hi,I am using self hosted runner (ubuntu) and I have added this action `android-actions/setup-android@v2` but the build fails with this error message.

```
Run android-actions/setup-android@v2
/workdir/_actions/android-actions/setup-android/v2/dist/index.js:354[6](https://github.com/wtag/android-mobile-app/actions/runs/5043540154/jobs/9045450586#step:4:7)
                    throw new Error(`Unable to locate executable file: ${tool}. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.`);
                          ^

Error: Unable to locate executable file: unzip. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
    at Object.<anonymous> (/workdir/_actions/android-actions/setup-android/v2/dist/index.js:3546:2[7](https://github.com/wtag/android-mobile-app/actions/runs/5043540154/jobs/9045450586#step:4:8))
    at Generator.next (<anonymous>)
    at fulfilled (/workdir/_actions/android-actions/setup-android/v2/dist/index.js:3357:5[8](https://github.com/wtag/android-mobile-app/actions/runs/5043540154/jobs/9045450586#step:4:9))
```

**Comment by cwfitzgerald** [comment]
Try installing the `unzip` tool using apt, that seems to be the tool it's missing.

**Comment by prashant-actyv** [comment]
its still not working.

**Comment by ViliusSutkus89** [comment]
@ash-wtag , your error message `Error: Unable to locate executable file: unzip` tells me that you are missing a tool called unzip. Could you install it and verify that it is available by running `unzip -v` in the console?

**Comment by ViliusSutkus89** [comment]
@prashant-actyv , I guess your error message isn't the same, is it?
